# Generated by Django 4.2 on 2024-03-07 14:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_hospitalprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
    ]
