# Generated by Django 4.2 on 2024-03-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_hospitalprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservice',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='profiles.hospitalprofile', verbose_name='Service offered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date the hospital details were updated '),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date the patient details were updated '),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date the hospital was added '),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date the patient was added '),
        ),
    ]
