# Generated by Django 4.2 on 2024-03-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_remove_hospitalservice_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='profiles.hospitalprofile', verbose_name='Services offered'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient Owner'),
        ),
    ]
