# Generated by Django 4.2 on 2024-03-08 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_alter_hospitalprofile_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Date the nurse was added ')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date the nurse details were updated ')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hospitalprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Date the doctor was added ')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date the doctor details were updated ')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.hospitalprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
