# Generated by Django 4.2 on 2024-03-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_nurse_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='profiles.hospitalservice', verbose_name='Services offered'),
        ),
    ]
