# Generated by Django 4.2 on 2024-03-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_hospitalprofile_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='user',
            new_name='name',
        ),
    ]
