# Generated by Django 4.2 on 2024-03-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_user_doctor_name_rename_user_nurse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='name',
            new_name='user',
        ),
    ]
