# Generated by Django 4.2 on 2024-03-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_name_doctor_user_rename_name_nurse_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='user',
            new_name='name',
        ),
    ]
