# Generated by Django 4.2 on 2024-03-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rename_user_doctor_name_rename_user_nurse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='profiles.location', verbose_name='Location of the hospital'),
        ),
    ]
