# Generated by Django 4.2 on 2024-03-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0013_alter_doctor_name_alter_nurse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='owner',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='profiles.location', verbose_name='Location of the patient'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.hospitalprofile', verbose_name='Hospital profile')),
                ('patient_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.patientprofile', verbose_name='Patient profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User profile')),
            ],
        ),
    ]
