# Generated by Django 4.2 on 2024-03-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_hospitalprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hospital_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.hospitalprofile', verbose_name='Hospital profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patient_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.patientprofile', verbose_name='Patient profile'),
        ),
    ]
