# Generated by Django 4.2 on 2024-02-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_specialization_doctor_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='departments',
            new_name='department',
        ),
    ]
